const APPID = '3d40e9758a09eca50f631a8f51be4b4f';
const BASE_URL = 'https://api.openweathermap.org/data/2.5/weather';
const WEATHER_ICON_URL = 'http://openweathermap.org/img/w';

const UPDATE_WEATHER_INFO = 'UPDATE_WEATHER_INFO';
const UPDATE_DISPLAY_FORMAT = 'UPDATE_DISPLAY_FORMAT';
const UPDATE_PREFERRED_CONVERSION = 'UPDATE_PREFERRED_CONVERSION';
const UPDATE_LOCATION = 'UPDATE_LOCATION';
const API_IN_PROGRESS = 'API_IN_PROGRESS';
const API_SUCCESS = 'API_SUCCESS';
const API_FAILURE = 'API_FAILURE';

const CELSIUS = 'Celsius';
const FARENHEIT = 'Farenheit';
const CITIES = ['Berlin', 'Frankfurt', 'Munich', 'Dresden'];

export {
    APPID,
    BASE_URL,
    WEATHER_ICON_URL,
    CITIES,
    CELSIUS,
    FARENHEIT,
    UPDATE_WEATHER_INFO,
    UPDATE_DISPLAY_FORMAT,
    UPDATE_PREFERRED_CONVERSION,
    UPDATE_LOCATION,
    API_IN_PROGRESS,
    API_SUCCESS,
    API_FAILURE
}
